### ISSUE TITLE
Klizanje po zidu

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG103-bekstvo-iz-lavirinta#2]
Umesto da kolizija sa zidom blokira igraca, stavite da kliza po zidu.

Na primer, ako je zid sa desne strane igraca, a igrac zeli da se pomera napred-desno, da se ne odbije kretanje u potpunosti, nego da se igrac krece uz zid unapred.

**Comment by Laleee** [comment]
Promenio sam obradu kolizije da zasebno gleda kretanje pravo i kretanje u stranu. Medjutim, ako je kamera okrenuta tako da i kretanje pravo izaziva koliziju igrac se nece pomeriti. Ako se ugao kamere postavi lepo, kreanje uz zid deluje glatko, inace se desava kao da igrac secka prilikom kretanja udesno ka zidu. U lokalu sam promenio da igrac bude sfera, a ne AABB, ipak nema nikakve razlike sto se tice tog seckanja, samo je provera za koliziju slozenija pa je i igrica sporija kada ima vise objekata (zidova).

**Comment by ivan-cukic-matf** [comment]
Nisam mislio na ovo. I kad dodje do kolizije, igrač može da se kreće - samo što mu se ne može dozvoliti da ode na poziciju na koju je hteo da ode, nego na tačku koja je najbliža toj poziciji, ali tako da nema kolizije.

Zamislite sledeće - imate beskonačan zid x < 0. Igrač je trenutno na (1, 1, 1) i pokušava da ode na (-1, -1, -1) ali ne može jer je ta tačka u zidu (x koordinata je -1). Koja je najbliža tačka njoj, a da nije unutar zida? Ortogonalna projekcija željene tačke na površ zida - (0, -1, -1).

U Vašem slučaju, nemate beskonačan zid, ali možete isto željenu tačku da projektujete na zid o koji ste trenutno udarili.

**Comment by Laleee** [comment]
S obizrom da su mi zidovi paralelni sa koordinatnim osama gledao sam zasebno x i z komponentu vektora kretanja i onu koja izaziva koliziju ignorisao. Sada igrac klizi kad se zakuca u zid pod nekim uglom.
